services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - hackathon-network

  frontend:
    build: ./frontend
    ports:
      - "7860:7860"
    networks:
      - hackathon-network

networks:
  hackathon-network:
    driver: bridge
